# Generated by Django 5.2.16 on 2026-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbif_key', models.IntegerField(blank=True, db_index=True, help_text='GBIF API usageKey', null=True, unique=True)),
                ('scientific_name', models.CharField(db_index=True, help_text='Full binomial scientific name', max_length=255)),
                ('common_name', models.CharField(blank=True, default='', help_text='Primary vernacular/common name', max_length=255)),
                ('kingdom', models.CharField(default='Plantae', max_length=100)),
                ('phylum', models.CharField(blank=True, default='', max_length=100)),
                ('class_name', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.CharField(blank=True, default='', max_length=100)),
                ('family', models.CharField(blank=True, default='', max_length=100)),
                ('genus', models.CharField(blank=True, default='', max_length=100)),
                ('native_region', models.JSONField(blank=True, default=dict, help_text='GeoJSON/Region metadata for origin mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['scientific_name'],
            },
        ),
    ]
