# Generated by Django 5.2.16 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='is_collection_favorite',
            field=models.BooleanField(default=False, help_text='Personal collection favourite preference'),
        ),
    ]
