# Generated by Django 5.2.16 on 2026-09-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_identification_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationkeyrun',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('superseded', 'Substituído')], default='active', max_length=10),
        ),
    ]
