# Generated by Django 5.2.16 on 2026-09-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_key_run_superseded'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationkeyrun',
            name='pending_note',
            field=models.TextField(blank=True),
        ),
    ]
