/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    borderRadius: {
      none: '0px',
      DEFAULT: '0px',
      sm: '0px',
      md: '0px',
      lg: '0px',
      xl: '0px',
      '2xl': '0px',
      '3xl': '0px',
      full: '0px',
    },
    extend: {
      colors: {
        lime: {
          DEFAULT: '#BDFF00',
          50: '#F2FFD6',
          100: '#E8FFB3',
          200: '#D9FF66',
          300: '#CBFF33',
          400: '#BDFF00',
          500: '#9AD600',
          600: '#78A800',
          700: '#567A00',
          800: '#344C00',
          900: '#121E00',
        },
        offwhite: '#F4EEDC',
        charcoal: '#171713',
        botanical: '#197A50',
        primary: '#4F46E5',
        'primary-container': '#BDFF00',
        secondary: '#5C3DF5',
        'surface-variant': '#FFD34E',
        amber: '#FFB000',
        critical: '#D83A52',
        info: '#3568FF',
        coral: '#FF6B4A',
        mint: '#65D6AD',
        lilac: '#C8B6FF',
        surface: '#FFFDF5',
        owned: '#BDFF00',
        missing: '#8A8A8A',
      },
      fontFamily: {
        sans: ['Lexend', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      spacing: {
        18: '4.5rem',
      },
      borderWidth: {
        DEFAULT: '2px',
        0: '0px',
        2: '2px',
        4: '4px',
      },
      boxShadow: {
        'hard': '5px 5px 0px 0px #171713',
        'hard-sm': '3px 3px 0px 0px #171713',
        'hard-lg': '8px 8px 0px 0px #171713',
        'hard-lime': '4px 4px 0px 0px #BDFF00',
        'hard-pressed': '1px 1px 0px 0px #171713',
        'none': 'none',
      },
      screens: {
        xs: '360px',
      },
    },
  },
  plugins: [],
};
