# Generated by Django 5.2.16 on 2026-07-20 19:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(help_text='Personal name for the specimen', max_length=100)),
                ('location_in_home', models.CharField(blank=True, default='', help_text='Room / microclimate location', max_length=100)),
                ('acquired_at', models.DateField(help_text='Date when the plant was acquired')),
                ('vitality_index', models.SmallIntegerField(default=100, help_text='Vitality score percentage (0–100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('soil_moisture', models.SmallIntegerField(default=50, help_text='Current soil moisture percentage (0–100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lux_intensity', models.IntegerField(default=1000, help_text='Estimated sunlight intensity (Lux)', validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.URLField(blank=True, default='', help_text='Specimen cover photograph URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(help_text='Linked canonical species catalog record', on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='catalog.species')),
            ],
            options={
                'ordering': ['-acquired_at'],
            },
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('repotting', 'Repotting'), ('observation', 'Observation')], help_text='Type of care activity', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time when care was performed')),
                ('notes', models.TextField(blank=True, default='', help_text='Free-text observations or notes')),
                ('specimen', models.ForeignKey(help_text='Linked specimen instance', on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='specimens.specimen')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
