# Generated by Django 5.2.16 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this specimen is active in the personal collection'),
        ),
    ]
