# Generated by Django 5.2.16 on 2026-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_key', models.CharField(db_index=True, help_text='Location key (e.g., "lat_-23.55_lon_-46.63")', max_length=100, unique=True)),
                ('temperature_c', models.FloatField(help_text='Current ambient temperature in Celsius')),
                ('humidity_pct', models.IntegerField(help_text='Relative humidity percentage')),
                ('weather_code', models.IntegerField(default=0, help_text='WMO weather code')),
                ('cached_at', models.DateTimeField(auto_now=True, help_text='Timestamp of cache capture')),
            ],
            options={
                'verbose_name_plural': 'weather caches',
            },
        ),
    ]
